package grige;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.IOException;

import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * Represents  a material/texture-agnostic animation that can be applied to any number of objects simultaneously.
 * 
 * Animations are loaded from text files generated by SpriteSheetPacker, and are of the form:
 * 
 * <animationFrame1Name> <x> <y> <width> <height>
 * <animationFrame2Name> ...
 * ...
 * etc
 * 
 * Currently partial animations are not supported. If you wish to create an animation from a subset of frames of another animation,
 * you need a new text file to describe that
 * 
 * Note that animations do not play automatically, for each GameObject that you give an animation to, you must manually play that animation
 * Attempting to play the animation on a GameObject that has no animation will cause no error, it will simply have no effect until an animation
 * is provided.
 */
public class Animation
{
	private static final Logger log = Logger.getLogger(Animation.class.getName());
	
	public static final int PLAY_MODE_NONE = 0;
	public static final int PLAY_MODE_LOOP = 1;
	public static final int PLAY_MODE_PINGPONG = 2;
	public static final int PLAY_MODE_ONCE = 3;
	
	private ArrayList<AABBI> frameQuads;
	
	private Animation()
	{
		frameQuads = new ArrayList<AABBI>();
	}
	
	private void addFrame(int x, int y, int w, int h)
	{
		frameQuads.add(new AABBI(x,y,w,h));
	}
	
	public AABBI getFrameBox(int frame)
	{
		if(frame >= frameQuads.size())
			return null;
		return frameQuads.get(frame);
	}
	
	public int length()
	{
		return frameQuads.size();
	}
	
	public static Animation load(String filepath)
	{
		File sourceFile = new File(filepath);
		
		log.info("Loading animation "+sourceFile.getAbsolutePath());
		if(!sourceFile.exists())
		{
			log.warning("Error, attempt to load non-existant file: "+filepath);
			return null;
		}
		
		try
		{
			FileReader fileIn = new FileReader(sourceFile);
			BufferedReader reader = new BufferedReader(fileIn);
			
			Animation anim = new Animation();
			
			while(reader.ready())
			{
				String newLine = reader.readLine();
				
				String[] lineElements = newLine.split(" ");
				
				anim.addFrame( 
						Integer.parseInt(lineElements[2]),
						Integer.parseInt(lineElements[3]),
						Integer.parseInt(lineElements[4]),
						Integer.parseInt(lineElements[5])
				);
			}
			
			reader.close();
			fileIn.close();
			
			return anim;
		
		}
		catch(FileNotFoundException fnfe)
		{
			log.log(Level.WARNING, "", fnfe);
		}
		catch(IOException ioe)
		{
			log.log(Level.WARNING, "", ioe);
		}
		
		return null;
	}
}
